apiVersion: v1
kind: Secret
metadata:
  name: diff-secrets-env
type: Opaque
stringData:
  DIFF_DT_CLIENT_ID: '12345'
  DIFF_DT_CLIENT_SECRET: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  DIFF_LOG_LEVEL: 'warn'
  DIFF_SECRET: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  DIFF_SALT: 'xxxxxxxxxxxxxxxx'
